### ISSUE TITLE
Error with capnp plugin

### ISSUE THREAD

**Issue by nathanielhourt** [kaos/wireshark-plugins#1]
I'm trying to use the capnp plugin, but it fails with this error:

```
Cap'n Proto RPC Protocol
    Segments: 1
        Segment: 0 ( 5 words )
            Data ( 40 bytes )
Lua Error: [string "/home/nathan/.config/wireshark/plugins/capnp...."]:116: attempt to index global 'capnp_schema' (a nil value)
```

I see this error for every CapnP message captured. This is with Wireshark 2.0.2 on ArchLinux, capnp 0.5.3.

Any ideas?

**Comment by kaos** [comment]
Hmm.. it's been a while since I used this, but it feels like it hasn't loaded all files in the plugins folder.
There is a `capnp_schema.lua` file that needs to be loaded in order for it to work.

Based on the info the README, wireshark loaded all lua files in the plugins folder automatically, so any globals set from any of the files would be available in any other. But in this case, it feels like it doesn't work like that.

Perhaps it is a config option in wireshark to control that, or something like that?

**Comment by ztlpn** [comment]
I've encountered this error too. It seems that since quite some time ago Lua plugins no longer load into global environment (i guess [this commit](https://code.wireshark.org/review/gitweb?p=wireshark.git;a=commit;h=8c2bb805742c918b933923947a533d098774da75) is to blame) so other files cannot see the `capnp_schema` table. See the attached pull request for the solution.

Thanks for the scripts BTW :)
